export * from "./types/index.js";
export { validateIR, loadIRFromObject, newRunId } from "./ir/validator.js";
export { GraphStore } from "./graph/graph-store.js";
export { EventBus, eventsToJsonl } from "./events/event-bus.js";
export { validateEvidence, buildSuccessEvidence, buildRejectedGateEvidence } from "./evidence/validator.js";
export {
  buildPlanningEvidence,
  buildSchedulingEvidence,
  buildSelectionEvidence,
  buildWorkerEvidence,
  buildGateEvidence,
  buildExecutionEvidence,
  validateEvidenceV21,
} from "./evidence/builders.js";
export { deriveRunState, canTransition, transitionNode } from "./state/run-state.js";
export { SmartMockExecutor, createSmartMockProvider } from "./executors/smart-mock-executor.js";
export { PatternAggregator } from "./learning/pattern-aggregator.js";
export {
  EvolveLoopController,
  SignalMiner,
  PatternDetector,
  NeedDetector,
  RootCauseAnalyzer,
  EvolutionCandidateGenerator,
  CandidateValidator,
  EvolveLoopStore,
  SyntheticFixtures,
  EVOLVE_THRESHOLDS,
  PIPELINE_HANDOFF_CONTRACT,
  submitEvolutionRequest,
  buildEvolutionRequest,
  LongitudinalEvolveLoop,
  PersistentSignalStore,
  CrossRunAggregator,
  LongitudinalNeedDetector,
  OutcomeTracker,
  ADAPTER_REGISTRY,
  LONGITUDINAL_THRESHOLDS,
  longitudinalFailureArc,
  sameExecutionTriple,
  diagnoseWithInventory,
  snapshotInventoryFromRegistry,
  attachEvolveLoopObserver,
  attachLiveEvolveLoop,
  AnalysisCadence,
  LiveAnalysisCoordinator,
  ObservationWindowManager,
  approveEvolutionRequestFixture,
  LIVE_CADENCE_DEFAULTS,
  ScopedAnalysisCadence,
  deriveScopeFromObservation,
  EVENT_COVERAGE,
  readGateResult,
  ingestGateResult,
} from "./evolveloop/index.js";
export type {
  RawObservation,
  NeedSignal,
  DetectedPattern,
  NeedCandidate,
  RootCauseAnalysis,
  EvolutionCandidate,
  EvolutionRequest,
  EvolveLoopRunResult,
  AutonomyLevel,
  CandidateType,
  EvolutionScopeClass,
  LongitudinalNeed,
  EvolutionOutcome,
  ObservationClass,
  NeedLifecycle,
  OutcomeKind,
  AnalysisScope,
  InventorySnapshot,
  SystemInventory,
  LiveCoordinatorOptions,
  LiveCadenceConfig,
  ObservationWindow,
  GateDecision,
  GateResult,
  GateSourceKind,
  EventCoverageMode,
} from "./evolveloop/index.js";

export { PolicyEngine } from "./policies/policy-engine.js";
export {
  POLICY_DEFAULTS,
  parseTimeoutMs,
  resolveExecutionBudget,
  createAccounting,
  remainingFeatureMs,
  featureTimedOut,
  recordProviderTried,
  type ExecutionBudget,
  type ResourceAccounting,
  type BudgetExhaustionCode,
} from "./policies/policy-engine.js";
export { RegistryClient, buildRegistryFromManifests } from "./registry/registry-client.js";
export {
  loadYamlFile,
  manifestToRegistryEntries,
  buildRegistryFromManifestFiles,
  loadPolicy,
  loadPoliciesFromDir,
} from "./registry/manifest-loader.js";
export { KnowledgeStore } from "./knowledge/knowledge-store.js";
export { FilesystemKnowledgeStore } from "./knowledge/filesystem-knowledge-store.js";
export type {
  KnowledgeBackend,
  KnowledgeBackendId,
  KnowledgeHealth,
  KnowledgeInspectResult,
} from "./knowledge/backend/types.js";
export { resolveKnowledgeBackend, resetKnowledgeBackendCache } from "./knowledge/backend/resolve.js";
export { WikiKnowledgeBackend, resolveWikiRoot, resolveWikiCliModule } from "./knowledge/backend/wiki-backend.js";
export { FakeKnowledgeBackend } from "./knowledge/backend/fake-backend.js";
export {
  loadMegaBrainProfile,
  loadEvolveLoopProfile,
  resolveKnowledgeBackendId,
  DEFAULT_PROFILE,
  type MegaBrainProfile,
  type EvolveLoopProfile,
} from "./config/profile.js";
export { MemoryStore } from "./memory/memory-store.js";
export { FilesystemMemoryStore } from "./memory/filesystem-memory-store.js";
export { JsonlEventPersister } from "./persistence/jsonl-event-persister.js";
export { resolveDataPaths, type DataPaths } from "./persistence/paths.js";
export { MetricsAccumulator } from "./telemetry/metrics-accumulator.js";
export {
  summarizeExecutionTrace,
  type ExecutionTraceInput,
  type ExecutionTraceSummary,
  type CapabilityCallSummary,
  type AuthorityDecisionSummary,
  type ExecutionErrorSummary,
} from "./telemetry/execution-trace.js";
export {
  buildSkillTelemetryRecord,
  emitSkillTelemetry,
  appendSkillTelemetryJsonl,
  recordSkillLifecycle,
  aggregateSkillTelemetry,
  loadSkillTelemetryFromDir,
  type SkillTelemetryRecord,
  type SkillTelemetryEventType,
  type SkillUsageAggregate,
  type ObservationWindow,
} from "./telemetry/skill-telemetry.js";
export {
  evaluateGrillMeRequired,
  evaluateGrillMeTransition,
  evaluateImageToCodeGate,
  skillGatesToRequireFlags,
  type GrillMeGateInput,
  type ImageToCodeGateInput,
  type SkillGateDecision,
  type GateStatus,
  type RiskTier,
} from "./policy/skill-gates.js";
export { Orchestrator } from "./orchestrator/orchestrator.js";
export { Scheduler } from "./scheduler/scheduler.js";
export { MockProvider, ProviderRouter, createMockProvider } from "./providers/mock-provider.js";
export {
  bootstrapProviders,
  loadProviderManifests,
  buildRegistryFromProvidersDir,
  padRegistryForMock,
  type ProviderMode,
  type ProviderBootstrapOptions,
  type ProviderBootstrapResult,
  type ProviderRegistration,
  type UnavailableProvider,
} from "./providers/bootstrap.js";
export {
  CursorSkillProvider,
  JobFileExecutor,
  CallbackSkillExecutor,
  evidenceFromShellResult,
  type SkillExecutor,
} from "./plugins/cursor-skill-provider.js";
export {
  AutonomousSkillExecutor,
  canExecuteAutonomously,
  resolveAutonomousModule,
  AUTONOMOUS_SANDBOX_STATUS,
  type SkillExecutorKind,
  type AutonomousSkillExecutorOptions,
} from "./plugins/autonomous-skill-executor.js";
export type {
  AutonomousSkillContext,
  AutonomousSkillHandler,
  AutonomousSkillHandlerResult,
  AutonomousPluginConfig,
} from "./plugins/skill-handler.js";
export { inputsFromRequest } from "./plugins/skill-handler.js";
export { PluginLoader, loadProviderFromManifest } from "./plugins/plugin-loader.js";
export { ExecutionEngine } from "./engine/execution-engine.js";
export { JobStore, type SkillJob, type SkillJobResult, type SkillJobStatus, type ClaimResult } from "./jobs/job-store.js";
export { SkillWorker, type SkillWorkerOptions, type SkillWorkerStats } from "./jobs/skill-worker.js";
export { invokePickup, buildPickupPrompt, type PickupPlan } from "./jobs/job-pickup.js";
export { jobResultToExecuteResult, loadEvidenceFile } from "./jobs/job-resume.js";
export {
  saveCheckpoint,
  loadCheckpoint,
  loadAndValidateCheckpoint,
  clearCheckpoint,
  listRecoverableExecutions,
  claimExecutionRecovery,
  releaseExecutionRecovery,
  reconcileInFlightGraph,
  validateCheckpoint,
  validateCheckpointSemantics,
  CHECKPOINT_SCHEMA_VERSION,
  type EngineCheckpoint,
  type CheckpointValidation,
  type SerializedAccounting,
  type DeliverySemantics,
  type NodeRecoveryClass,
} from "./jobs/checkpoint.js";
export {
  validateStructuredIntent,
  emitCapabilityIR,
  emitPlan,
  emitPlanOrThrow,
  validateExecutableIR,
  assertExecutableIR,
  RejectedBeforeExecutionError,
  REJECTED_BEFORE_EXECUTION,
  routerHas,
  type StructuredIntent,
  type IntentStep,
  type IntentValidationError,
  type PlanEmissionResult,
  type PlanEmissionSuccess,
  type PlanEmitterOptions,
  type PreflightOptions,
  type PreflightResult,
} from "./planning/index.js";
export {
  classifyFailure,
  shouldReplan,
  hashCapabilityIR,
  stampPlanLineage,
  applyReplanPreservingCompleted,
  DeterministicReplanner,
  UnavailableReplanner,
  type Replanner,
  type ReplanInput,
  type ReplanResult,
  type ReplanStrategy,
  type FailureClassification,
  type FailureDisposition,
} from "./replan/index.js";
export { ContractRegistry, loadContractsFromDir, parseContractRef } from "./contracts/contract-registry.js";
export { parseSemVer, satisfies, matchesPattern, contractRefVersion, contractRefId } from "./contracts/semver.js";
export type { ContractDocument, ContractCompatibilityResult } from "./contracts/contract-types.js";
export { buildRegistry, aggregateProviderStats } from "./registry/registry-builder.js";
export { loadJsonSchema, validateAgainstSchema } from "./schemas/schema-validator.js";
export { discoverAllManifests, discoverManifestForCapability } from "./discovery/provider-discovery.js";
export {
  authorize,
  CapabilityAuthority,
  createCapabilityAuthority,
  pathEscapesWorkspace,
  type AuthorityContext,
  type AuthorityRequest,
  type AuthorityResult,
  type AuthorityDecision,
} from "./authority/capability-authority.js";
export {
  filterRegistryByProfile,
  capabilitiesForProfile,
  CAPABILITY_PROFILES,
  type CapabilityProfile,
} from "./discovery/capability-profiles.js";
export {
  DeterministicProvider,
  createDeterministicProvider,
  DEFAULT_HANDLERS,
} from "./providers/deterministic/index.js";
export {
  buildAuthorityEvidence,
  buildRetrievalEvidence,
} from "./evidence/builders.js";
export * from "./capabilities/results.js";
export {
  evaluatePreExecute,
  type PreExecuteDecision,
  type PreExecuteInput,
  type PreExecuteResult,
  type RuntimeGateContext,
  type GateKind,
} from "./gates/index.js";
export {
  DefaultAgentExecutor,
  TestReasoningProvider,
  AgentBackedReplanner,
  LLMReplanner,
  assembleAgentExecutionRequest,
  validateAgentDecisionPayload,
  applyAgentDecisionToPlan,
  toPersistableDecisionMeta,
  applyReasoningUsageToAccounting,
  isTokenBudgetExhausted,
  assertNoForbiddenKeys,
  redactForbiddenKeys,
  FORBIDDEN_CONTEXT_KEY_PATTERN,
  readReasoningConfigFromEnv,
  createReasoningProvider,
  probeOllamaAvailable,
  probeCursorAvailable,
  OllamaReasoningProvider,
  CursorReasoningProvider,
  MockCursorReasoningProvider,
  resolveCursorApiKey,
  redactCursorSecrets,
  mapCursorError,
  extractJsonObject,
  normalizeProviderHttpError,
  REASONING_PROMPT_VERSION,
  LIVE_EVAL_CASES,
  LIVE_EVAL_SUITE_VERSION,
  runLiveEvalSuite,
  SE08_CURSOR_CASES,
  SE08_SUITE_VERSION,
  runSe08CursorSuite,
  runSe08CursorCase,
  type AgentExecutor,
  type AgentExecutionRequest,
  type AgentExecutionResult,
  type AgentDecision,
  type AgentDecisionType,
  type ReasoningProvider,
  type ReasoningRequest,
  type ReasoningResponse,
  type PersistableDecisionMeta,
  type ApplyDecisionResult,
  type ReasoningRuntimeConfig,
  type LiveEvalCase,
  type LiveEvalMetrics,
  type LiveCaseResult,
  type Se08Case,
  type Se08CaseResult,
  type CursorExecutionMode,
} from "./agent/index.js";
export * from "./backends/index.js";
export {
  validateRequirementsSpec,
  computeReadiness,
  requirementsGateAllowsArchitecture,
  buildRequirementsSpecFromProposal,
  buildRequirementsFromAgentDecision,
  emptyRequirementsSpec,
  computeRequirementHash,
  createRequirementsBaseline,
  createNextRequirementsVersion,
  diffRequirementsVersions,
  assertMutable,
  toArchitectureHandoff,
  RequirementsImmutabilityError,
  RequirementsArtifactStore,
  extractRequirementsProposal,
  extractAndBuild,
  assertNoCodeGeneration,
  buildRequirementsEvidence,
  runRequirementsFromText,
  runRequirementsFromAgentDecision,
  runRequirementsFromAgentResult,
  emitRequirementsTelemetry,
  REQUIREMENTS_EVENT_TYPES,
  type RequirementsSpec,
  type Requirement,
  type RequirementsValidationResult,
  type RequirementsExtractionInput,
  type RequirementsPipelineResult,
  type ArchitectureHandoff,
  type RequirementsChangeSet,
} from "./requirements/index.js";
export {
  validateArchitectureSpec,
  computeArchitectureReadiness,
  architectureGateAllowsTaskDecomposition,
  buildArchitectureSpecFromProposal,
  buildArchitectureFromAgentDecision,
  emptyArchitectureSpec,
  extractArchitectureProposal,
  extractAndBuildArchitecture,
  buildInvalidArchitectureFixtures,
  createArchitectureBaseline,
  createNextArchitectureVersion,
  diffArchitectureVersions,
  assertArchitectureMutable,
  toTaskDecompositionHandoff,
  ArchitectureImmutabilityError,
  ArchitectureArtifactStore,
  buildArchitectureEvidence,
  runArchitectureFromRequirements,
  runArchitectureFromAgentDecision,
  runArchitectureFromAgentResult,
  emitArchitectureTelemetry,
  ARCHITECTURE_EVENT_TYPES,
  type ArchitectureSpec,
  type ArchitectureComponent,
  type ArchitectureInterface,
  type ArchitectureDecision,
  type ArchitectureValidationResult,
  type ArchitectureChangeSet,
  type ArchitectureFeedback,
  type ArchitecturePipelineResult,
  type TaskDecompositionHandoff,
} from "./architecture/index.js";
export {
  validateTaskGraph,
  computeTaskGraphHealth,
  taskGraphGateAllowsExecution,
  buildTaskGraphFromProposal,
  buildTaskGraphFromAgentDecision,
  emptyTaskGraph,
  extractTaskGraphProposal,
  extractAndBuildTaskGraph,
  buildInvalidTaskGraphFixtures,
  createTaskGraphBaseline,
  createNextTaskGraphVersion,
  diffTaskGraphVersions,
  assertTaskGraphMutable,
  replaceTask,
  TaskGraphImmutabilityError,
  TaskGraphArtifactStore,
  buildTaskGraphEvidence,
  runTaskGraphFromSpecs,
  runTaskGraphFromAgentDecision,
  runTaskGraphFromAgentResult,
  toIrMappingHints,
  TASK_GRAPH_EVENT_TYPES,
  type EngineeringTask,
  type EngineeringTaskGraph,
  type TaskGraphValidationResult,
  type TaskGraphChangeSet,
  type TaskDependency,
  type TaskEvidenceRequirement,
  type TaskGraphPipelineResult,
  type TaskToIrMappingHint,
} from "./tasks/index.js";
export {
  Supervisor,
  AssignmentStore,
  SimulatedRuntimeBridge,
  ForbiddenDirectProviderBridge,
  evaluateAgentEligibility,
  selectEligibleAgents,
  canTransitionAssignment,
  assertTransition,
  InvalidAssignmentTransitionError,
  validateDelegationDecision,
  buildDelegationResult,
  buildDelegationEvidence,
  defaultAgentCatalog,
  listReadyTasks,
  decisionNeedsRuntime,
  type AgentAssignment,
  type DelegationRequest,
  type DelegationResult,
  type AgentContract,
  type SupervisorState,
  type RuntimeBridge,
  type DelegateTaskResult,
} from "./supervisor/index.js";
export {
  EngineeringWorker,
  WorkerCheckpointStore,
  buildWorkRequest,
  fixtureCorrectAddOps,
  parseImplementationProposal,
  applyWorkspaceOps,
  executeTestCommand,
  selectValidationCommands,
  buildValidationResult,
  classifyEngineeringFailure,
  buildEngineeringEvidence,
  assertWorkspaceOpScope,
  isForbiddenPath,
  isAllowedTestCommand,
  type EngineeringWorkRequest,
  type EngineeringWorkResult,
  type EngineeringValidationResult,
  type TestExecutionResult,
  type ImplementationProposalBody,
  type WorkspaceOp,
  type EngineeringWorkerCheckpoint,
} from "./engineering/index.js";
export {
  EngineeringReviewer,
  ReviewStore,
  buildReviewRequest,
  runDeterministicChecks,
  buildDiffSummary,
  implementationVersionFingerprint,
  assertReviewIndependence,
  DETERMINISTIC_REVIEWER_ID,
  ForbiddenReviewerExecutor,
  ForbiddenReviewerExecutionError,
  buildReviewEvidence,
  assertCompletionAllowed,
  type EngineeringReviewRequest,
  type EngineeringReviewResult,
  type ReviewFinding,
  type EngineeringReviewStatus,
} from "./engineering/index.js";
export {
  SoftwareEngineeringProject,
  materializeMiniCrmFixture,
  writeDeliveryMarkdown,
  MINICRM_BRIEF,
  ProjectCheckpointStore,
  auditCompositionSeams,
  type Se07BenchmarkOptions,
  type Se07BenchmarkResult,
  type ProjectPhase,
  type ProjectCheckpoint,
  type ProjectMetrics,
  type DeliveryArtifact,
  type TraceLink,
  type CompositionSeamAudit,
} from "./engineering/index.js";
